# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-27 13:59
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import redactor.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', redactor.fields.RedactorField(max_length=200)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='NewslettterRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=100)),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Qualification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100, null=True, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('description', redactor.fields.RedactorField(null=True)),
                ('job_roles', redactor.fields.RedactorField(null=True)),
                ('pathways', redactor.fields.RedactorField(null=True)),
                ('fees', redactor.fields.RedactorField(null=True)),
                ('packaging_rule', redactor.fields.RedactorField(null=True)),
                ('how_it_works', redactor.fields.RedactorField(null=True)),
                ('status', models.PositiveIntegerField(choices=[(0, 'Published'), (1, 'Requested')], default=0)),
                ('search_count', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='QualificationCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SkillAsessmentUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('phone', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(regex='^\\+?1?\\d{9,15}$')])),
                ('qualification_other', models.CharField(max_length=200, null=True)),
                ('experience_year', models.PositiveIntegerField(null=True)),
                ('experience_month', models.PositiveIntegerField(null=True)),
                ('experience_location', models.PositiveIntegerField(choices=[(0, 'Australia'), (1, 'Overseas'), (2, 'Others')])),
                ('formal_qualification', models.BooleanField(default=True)),
                ('formal_details', models.TextField(blank=True, null=True)),
                ('state', models.CharField(max_length=50)),
                ('comments', models.TextField()),
                ('qualification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.Qualification')),
                ('skills', models.ManyToManyField(to='bot.Skill')),
            ],
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dp', models.ImageField(upload_to='docs/images/testimonials')),
                ('name', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=200)),
                ('message', redactor.fields.RedactorField()),
            ],
        ),
        migrations.CreateModel(
            name='VisitorQuery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=200)),
                ('phone_number', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(regex='^\\+?1?\\d{9,15}$')])),
                ('message', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='qualification',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.QualificationCategory'),
        ),
    ]
