# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-04-07 15:40
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Qualification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='QualificationCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='SkillAsessmentUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('phone', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(regex='^\\+?1?\\d{9,15}$')])),
                ('qualification_other', models.CharField(max_length=200, null=True)),
                ('experience_year', models.PositiveIntegerField(null=True)),
                ('experience_month', models.PositiveIntegerField(null=True)),
                ('experience_location', models.PositiveIntegerField(choices=[(0, 'Australia'), (1, 'Overseas'), (2, 'Others')])),
                ('formal_qualification', models.BooleanField(default=True)),
                ('formal_details', models.TextField()),
                ('state', models.CharField(max_length=50)),
                ('comments', models.TextField()),
                ('qualification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.Qualification')),
            ],
        ),
        migrations.CreateModel(
            name='VisitorQuery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=200)),
                ('phone_number', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(regex='^\\+?1?\\d{9,15}$')])),
                ('message', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='UserDetail',
        ),
        migrations.AddField(
            model_name='qualification',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.QualificationCategory'),
        ),
    ]
