# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-04-08 12:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_auto_20170407_1540'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewslettterRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Testimonials',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dp', models.FileField(upload_to='docs/images/testimonials')),
                ('name', models.CharField(max_length=100)),
                ('is_who', models.CharField(max_length=200)),
                ('message', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='qualification',
            name='code',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='qualification',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='qualification',
            name='status',
            field=models.PositiveIntegerField(choices=[(0, 'Published'), (1, 'Requested')], default=0),
        ),
    ]
