# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-29 04:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_qualificationcategory_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qualificationcategory',
            name='description',
        ),
        migrations.RemoveField(
            model_name='qualificationcategory',
            name='image',
        ),
        migrations.AddField(
            model_name='qualificationcategory',
            name='slug',
            field=models.SlugField(max_length=100, null=True),
        ),
    ]
