# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-04-08 17:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0004_auto_20170408_1650'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skillasessmentuser',
            name='skills',
        ),
        migrations.AddField(
            model_name='skillasessmentuser',
            name='skills',
            field=models.ManyToManyField(null=True, to='bot.Skill'),
        ),
    ]
