# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-29 05:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0004_auto_20170429_0447'),
    ]

    operations = [
        migrations.AddField(
            model_name='qualification',
            name='duration',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='qualification',
            name='study_mode',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
