# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-04-08 17:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0006_auto_20170408_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skillasessmentuser',
            name='formal_details',
            field=models.TextField(blank=True, null=True),
        ),
    ]
