# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-04-10 17:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0008_emailcontent'),
    ]

    operations = [
        migrations.AddField(
            model_name='qualification',
            name='search_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
