# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-04-11 17:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0009_qualification_search_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailcontent',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='skillasessmentuser',
            name='skills',
            field=models.ManyToManyField(to='bot.Skill'),
        ),
    ]
