# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-04-12 14:09
from __future__ import unicode_literals

from django.db import migrations, models
import redactor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0010_auto_20170411_1714'),
    ]

    operations = [
        migrations.AddField(
            model_name='qualification',
            name='fees',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='qualification',
            name='job_roles',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='qualification',
            name='packaging_rule',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='emailcontent',
            name='body',
            field=redactor.fields.RedactorField(max_length=200),
        ),
    ]
