# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-04-12 15:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0011_auto_20170412_1409'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skillasessmentuser',
            old_name='first_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='skillasessmentuser',
            name='last_name',
        ),
    ]
