# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-04-18 16:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0012_auto_20170412_1559'),
    ]

    operations = [
        migrations.AddField(
            model_name='newslettterrequest',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
