# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-04-18 18:01
from __future__ import unicode_literals

from django.db import migrations
import redactor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0014_auto_20170418_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonial',
            name='message',
            field=redactor.fields.RedactorField(),
        ),
    ]
