# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-04-22 12:07
from __future__ import unicode_literals

from django.db import migrations
import redactor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0016_auto_20170422_0653'),
    ]

    operations = [
        migrations.AddField(
            model_name='qualification',
            name='how_it_works',
            field=redactor.fields.RedactorField(null=True),
        ),
        migrations.AddField(
            model_name='qualification',
            name='pathways',
            field=redactor.fields.RedactorField(null=True),
        ),
    ]
