# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-24 16:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0017_auto_20170422_1207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonial',
            name='dp',
            field=models.ImageField(upload_to='docs/images/testimonials'),
        ),
    ]
